import Foundation

enum PathError: Error, CustomStringConvertible {
    case noProjectFound
    case multipleProjectsFound([String])
    case breakpointFileNotFound(String)

    var description: String {
        switch self {
        case .noProjectFound:
            return "No .xcworkspace or .xcodeproj found in the repo root. Run 'xmark config --set project=MyApp.xcworkspace' to configure one."
        case .multipleProjectsFound(let names):
            return "Multiple Xcode projects found: \(names.joined(separator: ", ")). Run 'xmark config --set project=<name>' to specify which to use."
        case .breakpointFileNotFound(let path):
            return "Breakpoint file not found at: \(path)"
        }
    }
}

enum PathUtilities {
    static var username: String {
        ProcessInfo.processInfo.environment["USER"] ?? NSUserName()
    }

    // MARK: - Project file resolution

    /// Resolves the Xcode project file URL from config or by auto-discovery.
    static func projectURL(repoRoot: URL, configuredProject: String?) throws -> URL {
        if let configured = configuredProject {
            return repoRoot.appendingPathComponent(configured)
        }
        return try autoDetectProject(in: repoRoot)
    }

    private static func autoDetectProject(in repoRoot: URL) throws -> URL {
        let fm = FileManager.default
        let contents = try fm.contentsOfDirectory(atPath: repoRoot.path)

        let projects = contents.filter {
            $0.hasSuffix(".xcworkspace") || $0.hasSuffix(".xcodeproj")
        }
        // Prefer .xcworkspace over .xcodeproj when both exist with the same stem
        let workspaces = projects.filter { $0.hasSuffix(".xcworkspace") }
        let xcodeprojs = projects.filter { $0.hasSuffix(".xcodeproj") }

        // Filter out workspaces that are generated by SPM inside an xcodeproj
        let realWorkspaces = workspaces.filter { ws in
            !xcodeprojs.contains(where: { proj in
                ws == proj.replacingOccurrences(of: ".xcodeproj", with: ".xcworkspace")
            })
        }

        let candidates = realWorkspaces.isEmpty ? xcodeprojs : realWorkspaces

        if candidates.isEmpty {
            throw PathError.noProjectFound
        }
        if candidates.count > 1 {
            throw PathError.multipleProjectsFound(candidates)
        }

        return repoRoot.appendingPathComponent(candidates[0])
    }

    // MARK: - Breakpoint file path

    /// Returns the path to Breakpoints_v2.xcbkptlist inside the given project file.
    ///
    /// Xcode 16+ stores breakpoints in xcuserdata/<user>.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist.
    /// Older versions used xcuserdata/<user>.xcuserdatad/Breakpoints_v2.xcbkptlist directly.
    /// This function checks for the newer path first and falls back to the legacy path.
    static func breakpointFileURL(projectURL: URL) -> URL {
        let userDataDir = projectURL
            .appendingPathComponent("xcuserdata")
            .appendingPathComponent("\(username).xcuserdatad")

        let newPath = userDataDir
            .appendingPathComponent("xcdebugger")
            .appendingPathComponent("Breakpoints_v2.xcbkptlist")

        let legacyPath = userDataDir
            .appendingPathComponent("Breakpoints_v2.xcbkptlist")

        // Prefer the newer xcdebugger/ path if it exists; fall back to legacy
        if FileManager.default.fileExists(atPath: newPath.path) {
            return newPath
        }
        if FileManager.default.fileExists(atPath: legacyPath.path) {
            return legacyPath
        }
        // Neither exists yet — default to the newer path so xmark creates it in the right place
        return newPath
    }
}
