import Testing
import Foundation
@testable import xptCore

struct PathUtilitiesTests {

    // MARK: - selectProject

    @Test func selectProjectNoProjectThrows() {
        #expect(throws: PathError.self) {
            try PathUtilities.selectProject(from: [])
        }
    }

    @Test func selectProjectSingleWorkspace() throws {
        let result = try PathUtilities.selectProject(from: ["MyApp.xcworkspace"])
        #expect(result == "MyApp.xcworkspace")
    }

    @Test func selectProjectSingleXcodeproj() throws {
        let result = try PathUtilities.selectProject(from: ["MyApp.xcodeproj"])
        #expect(result == "MyApp.xcodeproj")
    }

    @Test func selectProjectPrefersWorkspaceOverXcodeproj() throws {
        // When workspace has a DIFFERENT stem than xcodeproj, both are candidates
        // but workspace wins since realWorkspaces is not empty
        let result = try PathUtilities.selectProject(from: ["MyApp.xcworkspace", "Other.xcodeproj"])
        #expect(result == "MyApp.xcworkspace")
    }

    @Test func selectProjectFiltersSPMGeneratedWorkspace() throws {
        // MyApp.xcworkspace is generated by MyApp.xcodeproj (same stem) — filter it out
        // This leaves only MyApp.xcodeproj
        let result = try PathUtilities.selectProject(from: ["MyApp.xcodeproj", "MyApp.xcworkspace"])
        #expect(result == "MyApp.xcodeproj")
    }

    @Test func selectProjectMultipleCandidatesThrows() {
        #expect(throws: PathError.self) {
            try PathUtilities.selectProject(from: ["App1.xcworkspace", "App2.xcworkspace"])
        }
    }

    // MARK: - projectURL traversal guard

    @Test func traversalOutsideRepoThrows() {
        let repoRoot = URL(fileURLWithPath: "/tmp/testrepo")
        #expect(throws: PathError.self) {
            try PathUtilities.projectURL(repoRoot: repoRoot, configuredProject: "../../etc/passwd")
        }
    }

    @Test func traversalInsideRepoSucceeds() throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        // A path with ../ that still stays inside the repo root should succeed
        let subdir = tmp.appendingPathComponent("subdir")
        try FileManager.default.createDirectory(at: subdir, withIntermediateDirectories: true)

        let result = try PathUtilities.projectURL(repoRoot: tmp, configuredProject: "subdir/../MyApp.xcworkspace")
        #expect(result.path == tmp.appendingPathComponent("MyApp.xcworkspace").standardizedFileURL.path)
    }

    @Test func simpleRelativePathSucceeds() throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        let result = try PathUtilities.projectURL(repoRoot: tmp, configuredProject: "MyApp.xcworkspace")
        #expect(result.path.hasSuffix("MyApp.xcworkspace"))
    }
}
